name: Caminus
main: us.camin.Plugin
author: Trever Fischer <team@camin.us>
website: http://camin.us/
version: ${version}
commands:
    motd:
        description: Displays the MOTD
        usage: /<command>
permissions:
    caminus.*:
        default: op
        description: Allows use of all caminus permissions
        children:
            caminus.whitelisted: true
            caminus.freedoorday: true
    caminus.freedoorday:
        default: false
        description: Enables free half door day
    caminus.whitelisted:
        default: op
        description: Allows user to bypass caminus API whitelisting

