name: Caminus
main: us.camin.Plugin
author: Trever Fischer <team@camin.us>
website: http://camin.us/
version: ${version}
load: startup
depend: [Vault]
commands:
    motd:
        description: Displays the MOTD
        usage: /<command>
    vomit:
        description: Causes a player to vomit blocks
        usage: /<command> player quantity item
    balance:
        description: Displays your balance
        usage: /<command>
    vaultmaster:
        description: Create a vaultmaster NPC at your current location.
permissions:
    caminus.*:
        default: op
        description: Allows use of all caminus permissions
        children:
            caminus.whitelisted: true
            caminus.freedoorday: true
            caminus.vomit: true
            caminus.vaultmaster: true
    caminus.freedoorday:
        default: false
        description: Enables free half door day
    caminus.vomit:
        default: op
        description: Enables /vomit
    caminus.whitelisted:
        default: op
        description: Allows user to bypass caminus API whitelisting
    caminus.vaultmaster:
        default: op
        description: Allows creation of vaultmasters, interfaces to the vault system.
